/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OkrsRouteImport } from './routes/okrs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InitiativesIndexRouteImport } from './routes/initiatives.index'
import { Route as InitiativesInitiativeIdRouteImport } from './routes/initiatives.$initiativeId'

const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OkrsRoute = OkrsRouteImport.update({
  id: '/okrs',
  path: '/okrs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesIndexRoute = InitiativesIndexRouteImport.update({
  id: '/initiatives/',
  path: '/initiatives/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesInitiativeIdRoute = InitiativesInitiativeIdRouteImport.update({
  id: '/initiatives/$initiativeId',
  path: '/initiatives/$initiativeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/okrs': typeof OkrsRoute
  '/playground': typeof PlaygroundRoute
  '/report': typeof ReportRoute
  '/style-guide': typeof StyleGuideRoute
  '/initiatives/$initiativeId': typeof InitiativesInitiativeIdRoute
  '/initiatives/': typeof InitiativesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/okrs': typeof OkrsRoute
  '/playground': typeof PlaygroundRoute
  '/report': typeof ReportRoute
  '/style-guide': typeof StyleGuideRoute
  '/initiatives/$initiativeId': typeof InitiativesInitiativeIdRoute
  '/initiatives': typeof InitiativesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/okrs': typeof OkrsRoute
  '/playground': typeof PlaygroundRoute
  '/report': typeof ReportRoute
  '/style-guide': typeof StyleGuideRoute
  '/initiatives/$initiativeId': typeof InitiativesInitiativeIdRoute
  '/initiatives/': typeof InitiativesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/okrs'
    | '/playground'
    | '/report'
    | '/style-guide'
    | '/initiatives/$initiativeId'
    | '/initiatives/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/okrs'
    | '/playground'
    | '/report'
    | '/style-guide'
    | '/initiatives/$initiativeId'
    | '/initiatives'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/okrs'
    | '/playground'
    | '/report'
    | '/style-guide'
    | '/initiatives/$initiativeId'
    | '/initiatives/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OkrsRoute: typeof OkrsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ReportRoute: typeof ReportRoute
  StyleGuideRoute: typeof StyleGuideRoute
  InitiativesInitiativeIdRoute: typeof InitiativesInitiativeIdRoute
  InitiativesIndexRoute: typeof InitiativesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okrs': {
      id: '/okrs'
      path: '/okrs'
      fullPath: '/okrs'
      preLoaderRoute: typeof OkrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/': {
      id: '/initiatives/'
      path: '/initiatives'
      fullPath: '/initiatives/'
      preLoaderRoute: typeof InitiativesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/$initiativeId': {
      id: '/initiatives/$initiativeId'
      path: '/initiatives/$initiativeId'
      fullPath: '/initiatives/$initiativeId'
      preLoaderRoute: typeof InitiativesInitiativeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OkrsRoute: OkrsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ReportRoute: ReportRoute,
  StyleGuideRoute: StyleGuideRoute,
  InitiativesInitiativeIdRoute: InitiativesInitiativeIdRoute,
  InitiativesIndexRoute: InitiativesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
