/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OkrsRouteImport } from './routes/okrs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InitiativesIndexRouteImport } from './routes/initiatives.index'
import { Route as InitiativesInitiativeIdRouteImport } from './routes/initiatives.$initiativeId'
import { Route as ApiVoiceTokenRouteImport } from './routes/api/voice-token'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicRoleSyncRouteImport } from './routes/api/public/role-sync'
import { Route as ApiPublicOpStructureSyncRouteImport } from './routes/api/public/op-structure-sync'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OkrsRoute = OkrsRouteImport.update({
  id: '/okrs',
  path: '/okrs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesIndexRoute = InitiativesIndexRouteImport.update({
  id: '/initiatives/',
  path: '/initiatives/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesInitiativeIdRoute = InitiativesInitiativeIdRouteImport.update({
  id: '/initiatives/$initiativeId',
  path: '/initiatives/$initiativeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTokenRoute = ApiVoiceTokenRouteImport.update({
  id: '/api/voice-token',
  path: '/api/voice-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRoleSyncRoute = ApiPublicRoleSyncRouteImport.update({
  id: '/api/public/role-sync',
  path: '/api/public/role-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpStructureSyncRoute =
  ApiPublicOpStructureSyncRouteImport.update({
    id: '/api/public/op-structure-sync',
    path: '/api/public/op-structure-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/auth': typeof AuthRoute
  '/okrs': typeof OkrsRoute
  '/playground': typeof PlaygroundRoute
  '/report': typeof ReportRoute
  '/style-guide': typeof StyleGuideRoute
  '/voice': typeof VoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice-token': typeof ApiVoiceTokenRoute
  '/initiatives/$initiativeId': typeof InitiativesInitiativeIdRoute
  '/initiatives/': typeof InitiativesIndexRoute
  '/api/public/op-structure-sync': typeof ApiPublicOpStructureSyncRoute
  '/api/public/role-sync': typeof ApiPublicRoleSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/auth': typeof AuthRoute
  '/okrs': typeof OkrsRoute
  '/playground': typeof PlaygroundRoute
  '/report': typeof ReportRoute
  '/style-guide': typeof StyleGuideRoute
  '/voice': typeof VoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice-token': typeof ApiVoiceTokenRoute
  '/initiatives/$initiativeId': typeof InitiativesInitiativeIdRoute
  '/initiatives': typeof InitiativesIndexRoute
  '/api/public/op-structure-sync': typeof ApiPublicOpStructureSyncRoute
  '/api/public/role-sync': typeof ApiPublicRoleSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/auth': typeof AuthRoute
  '/okrs': typeof OkrsRoute
  '/playground': typeof PlaygroundRoute
  '/report': typeof ReportRoute
  '/style-guide': typeof StyleGuideRoute
  '/voice': typeof VoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voice-token': typeof ApiVoiceTokenRoute
  '/initiatives/$initiativeId': typeof InitiativesInitiativeIdRoute
  '/initiatives/': typeof InitiativesIndexRoute
  '/api/public/op-structure-sync': typeof ApiPublicOpStructureSyncRoute
  '/api/public/role-sync': typeof ApiPublicRoleSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/auth'
    | '/okrs'
    | '/playground'
    | '/report'
    | '/style-guide'
    | '/voice'
    | '/api/chat'
    | '/api/voice-token'
    | '/initiatives/$initiativeId'
    | '/initiatives/'
    | '/api/public/op-structure-sync'
    | '/api/public/role-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/auth'
    | '/okrs'
    | '/playground'
    | '/report'
    | '/style-guide'
    | '/voice'
    | '/api/chat'
    | '/api/voice-token'
    | '/initiatives/$initiativeId'
    | '/initiatives'
    | '/api/public/op-structure-sync'
    | '/api/public/role-sync'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/auth'
    | '/okrs'
    | '/playground'
    | '/report'
    | '/style-guide'
    | '/voice'
    | '/api/chat'
    | '/api/voice-token'
    | '/initiatives/$initiativeId'
    | '/initiatives/'
    | '/api/public/op-structure-sync'
    | '/api/public/role-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AuthRoute: typeof AuthRoute
  OkrsRoute: typeof OkrsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ReportRoute: typeof ReportRoute
  StyleGuideRoute: typeof StyleGuideRoute
  VoiceRoute: typeof VoiceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiVoiceTokenRoute: typeof ApiVoiceTokenRoute
  InitiativesInitiativeIdRoute: typeof InitiativesInitiativeIdRoute
  InitiativesIndexRoute: typeof InitiativesIndexRoute
  ApiPublicOpStructureSyncRoute: typeof ApiPublicOpStructureSyncRoute
  ApiPublicRoleSyncRoute: typeof ApiPublicRoleSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okrs': {
      id: '/okrs'
      path: '/okrs'
      fullPath: '/okrs'
      preLoaderRoute: typeof OkrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/': {
      id: '/initiatives/'
      path: '/initiatives'
      fullPath: '/initiatives/'
      preLoaderRoute: typeof InitiativesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/$initiativeId': {
      id: '/initiatives/$initiativeId'
      path: '/initiatives/$initiativeId'
      fullPath: '/initiatives/$initiativeId'
      preLoaderRoute: typeof InitiativesInitiativeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-token': {
      id: '/api/voice-token'
      path: '/api/voice-token'
      fullPath: '/api/voice-token'
      preLoaderRoute: typeof ApiVoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/role-sync': {
      id: '/api/public/role-sync'
      path: '/api/public/role-sync'
      fullPath: '/api/public/role-sync'
      preLoaderRoute: typeof ApiPublicRoleSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/op-structure-sync': {
      id: '/api/public/op-structure-sync'
      path: '/api/public/op-structure-sync'
      fullPath: '/api/public/op-structure-sync'
      preLoaderRoute: typeof ApiPublicOpStructureSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AuthRoute: AuthRoute,
  OkrsRoute: OkrsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ReportRoute: ReportRoute,
  StyleGuideRoute: StyleGuideRoute,
  VoiceRoute: VoiceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiVoiceTokenRoute: ApiVoiceTokenRoute,
  InitiativesInitiativeIdRoute: InitiativesInitiativeIdRoute,
  InitiativesIndexRoute: InitiativesIndexRoute,
  ApiPublicOpStructureSyncRoute: ApiPublicOpStructureSyncRoute,
  ApiPublicRoleSyncRoute: ApiPublicRoleSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
